
services:
  postgres:
    image: postgres:9.2
    container_name: product-command
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=product-command
      - TZ=GMT
    volumes:
      - ./data/command/postgres:/var/lib/postgres/data
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 5533:5432
