---
spring:
  application:
    name: product-command
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5533/product-command
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgresSQLDialect
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      group-id: products-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    
server:
  port: 8083

