
services:
  postgres:
    image: postgres:9.2
    container_name: product-query
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=product-query
      - TZ=GMT
    volumes:
      - "./data/query/postgres:/var/lib/postgres/data"
    ports:
      - 5544:5432

